/**
 * Assessment ID constants
 *
 * IDs are generated once and stored as constants to ensure stability.
 * Format: {type}-{slug}-{random}
 *
 * In production, these should be generated by the backend and stored in the database.
 */

// General Assessment IDs
export const ASSESSMENT_ID_FRONTEND = 'gen-front-end-x7k9w2';
export const ASSESSMENT_ID_BACKEND = 'gen-back-end-a3m7n1';
export const ASSESSMENT_ID_FULLSTACK = 'gen-full-stack-p8q4r5';

// Skill Assessment IDs
export const ASSESSMENT_ID_TYPESCRIPT = 'skill-typescript-b9c2d3';
export const ASSESSMENT_ID_NODEJS = 'skill-nodejs-e4f5g6';
export const ASSESSMENT_ID_CSS = 'skill-css-h7j8k9';
export const ASSESSMENT_ID_SQL = 'skill-database-sql-m1n2p3';
export const ASSESSMENT_ID_REACT = 'skill-react-t4u5v6';
export const ASSESSMENT_ID_JAVASCRIPT = 'skill-javascript-w7x8y9';
export const ASSESSMENT_ID_GIT = 'skill-git-version-control-z1a2b3';
