/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParseCVRouteImport } from './routes/parseCV'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ResultSessionIdRouteImport } from './routes/result.$sessionId'
import { Route as QuizSessionIdRouteImport } from './routes/quiz.$sessionId'
import { Route as AuthVerificationRouteImport } from './routes/_auth/verification'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAppRouteRouteImport } from './routes/_app/app/route'
import { Route as PublicTermsIndexRouteImport } from './routes/_public/terms/index'
import { Route as PublicFeaturesIndexRouteImport } from './routes/_public/features/index'
import { Route as PublicAboutUsIndexRouteImport } from './routes/_public/about-us/index'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as AppAppParseCvIndexRouteImport } from './routes/_app/app/parse-cv/index'
import { Route as AppAppHistoryIndexRouteImport } from './routes/_app/app/history/index'
import { Route as AppAppCertificationIndexRouteImport } from './routes/_app/app/certification/index'
import { Route as AppAppCertificateVerificationIndexRouteImport } from './routes/_app/app/certificate-verification/index'
import { Route as AppAppAssessmentIndexRouteImport } from './routes/_app/app/assessment/index'
import { Route as AppAppAccountSettingsIndexRouteImport } from './routes/_app/app/account-settings/index'
import { Route as AppAppAssessmentAssessmentIdRouteRouteImport } from './routes/_app/app/assessment/$assessmentId/route'
import { Route as AppAppAssessmentAssessmentIdIndexRouteImport } from './routes/_app/app/assessment/$assessmentId/index'

const ParseCVRoute = ParseCVRouteImport.update({
  id: '/parseCV',
  path: '/parseCV',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ResultSessionIdRoute = ResultSessionIdRouteImport.update({
  id: '/result/$sessionId',
  path: '/result/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdRoute = QuizSessionIdRouteImport.update({
  id: '/quiz/$sessionId',
  path: '/quiz/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificationRoute = AuthVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppRouteRoute = AppAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicTermsIndexRoute = PublicTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFeaturesIndexRoute = PublicFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutUsIndexRoute = PublicAboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppParseCvIndexRoute = AppAppParseCvIndexRouteImport.update({
  id: '/parse-cv/',
  path: '/parse-cv/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppHistoryIndexRoute = AppAppHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppCertificationIndexRoute =
  AppAppCertificationIndexRouteImport.update({
    id: '/certification/',
    path: '/certification/',
    getParentRoute: () => AppAppRouteRoute,
  } as any)
const AppAppCertificateVerificationIndexRoute =
  AppAppCertificateVerificationIndexRouteImport.update({
    id: '/certificate-verification/',
    path: '/certificate-verification/',
    getParentRoute: () => AppAppRouteRoute,
  } as any)
const AppAppAssessmentIndexRoute = AppAppAssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppAccountSettingsIndexRoute =
  AppAppAccountSettingsIndexRouteImport.update({
    id: '/account-settings/',
    path: '/account-settings/',
    getParentRoute: () => AppAppRouteRoute,
  } as any)
const AppAppAssessmentAssessmentIdRouteRoute =
  AppAppAssessmentAssessmentIdRouteRouteImport.update({
    id: '/assessment/$assessmentId',
    path: '/assessment/$assessmentId',
    getParentRoute: () => AppAppRouteRoute,
  } as any)
const AppAppAssessmentAssessmentIdIndexRoute =
  AppAppAssessmentAssessmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAppAssessmentAssessmentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/parseCV': typeof ParseCVRoute
  '/app': typeof AppAppRouteRouteWithChildren
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/verification': typeof AuthVerificationRoute
  '/quiz/$sessionId': typeof QuizSessionIdRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/app/': typeof AppAppIndexRoute
  '/about-us/': typeof PublicAboutUsIndexRoute
  '/features/': typeof PublicFeaturesIndexRoute
  '/terms/': typeof PublicTermsIndexRoute
  '/app/assessment/$assessmentId': typeof AppAppAssessmentAssessmentIdRouteRouteWithChildren
  '/app/account-settings/': typeof AppAppAccountSettingsIndexRoute
  '/app/assessment/': typeof AppAppAssessmentIndexRoute
  '/app/certificate-verification/': typeof AppAppCertificateVerificationIndexRoute
  '/app/certification/': typeof AppAppCertificationIndexRoute
  '/app/history/': typeof AppAppHistoryIndexRoute
  '/app/parse-cv/': typeof AppAppParseCvIndexRoute
  '/app/assessment/$assessmentId/': typeof AppAppAssessmentAssessmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/parseCV': typeof ParseCVRoute
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/verification': typeof AuthVerificationRoute
  '/quiz/$sessionId': typeof QuizSessionIdRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/app': typeof AppAppIndexRoute
  '/about-us': typeof PublicAboutUsIndexRoute
  '/features': typeof PublicFeaturesIndexRoute
  '/terms': typeof PublicTermsIndexRoute
  '/app/account-settings': typeof AppAppAccountSettingsIndexRoute
  '/app/assessment': typeof AppAppAssessmentIndexRoute
  '/app/certificate-verification': typeof AppAppCertificateVerificationIndexRoute
  '/app/certification': typeof AppAppCertificationIndexRoute
  '/app/history': typeof AppAppHistoryIndexRoute
  '/app/parse-cv': typeof AppAppParseCvIndexRoute
  '/app/assessment/$assessmentId': typeof AppAppAssessmentAssessmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/parseCV': typeof ParseCVRoute
  '/_app/app': typeof AppAppRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/verification': typeof AuthVerificationRoute
  '/quiz/$sessionId': typeof QuizSessionIdRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_public/about-us/': typeof PublicAboutUsIndexRoute
  '/_public/features/': typeof PublicFeaturesIndexRoute
  '/_public/terms/': typeof PublicTermsIndexRoute
  '/_app/app/assessment/$assessmentId': typeof AppAppAssessmentAssessmentIdRouteRouteWithChildren
  '/_app/app/account-settings/': typeof AppAppAccountSettingsIndexRoute
  '/_app/app/assessment/': typeof AppAppAssessmentIndexRoute
  '/_app/app/certificate-verification/': typeof AppAppCertificateVerificationIndexRoute
  '/_app/app/certification/': typeof AppAppCertificationIndexRoute
  '/_app/app/history/': typeof AppAppHistoryIndexRoute
  '/_app/app/parse-cv/': typeof AppAppParseCvIndexRoute
  '/_app/app/assessment/$assessmentId/': typeof AppAppAssessmentAssessmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parseCV'
    | '/app'
    | '/$'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/verification'
    | '/quiz/$sessionId'
    | '/result/$sessionId'
    | '/app/'
    | '/about-us/'
    | '/features/'
    | '/terms/'
    | '/app/assessment/$assessmentId'
    | '/app/account-settings/'
    | '/app/assessment/'
    | '/app/certificate-verification/'
    | '/app/certification/'
    | '/app/history/'
    | '/app/parse-cv/'
    | '/app/assessment/$assessmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parseCV'
    | '/$'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/verification'
    | '/quiz/$sessionId'
    | '/result/$sessionId'
    | '/app'
    | '/about-us'
    | '/features'
    | '/terms'
    | '/app/account-settings'
    | '/app/assessment'
    | '/app/certificate-verification'
    | '/app/certification'
    | '/app/history'
    | '/app/parse-cv'
    | '/app/assessment/$assessmentId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_public'
    | '/parseCV'
    | '/_app/app'
    | '/_app/$'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/register'
    | '/_auth/verification'
    | '/quiz/$sessionId'
    | '/result/$sessionId'
    | '/_public/'
    | '/_app/app/'
    | '/_public/about-us/'
    | '/_public/features/'
    | '/_public/terms/'
    | '/_app/app/assessment/$assessmentId'
    | '/_app/app/account-settings/'
    | '/_app/app/assessment/'
    | '/_app/app/certificate-verification/'
    | '/_app/app/certification/'
    | '/_app/app/history/'
    | '/_app/app/parse-cv/'
    | '/_app/app/assessment/$assessmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ParseCVRoute: typeof ParseCVRoute
  QuizSessionIdRoute: typeof QuizSessionIdRoute
  ResultSessionIdRoute: typeof ResultSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parseCV': {
      id: '/parseCV'
      path: '/parseCV'
      fullPath: '/parseCV'
      preLoaderRoute: typeof ParseCVRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/result/$sessionId': {
      id: '/result/$sessionId'
      path: '/result/$sessionId'
      fullPath: '/result/$sessionId'
      preLoaderRoute: typeof ResultSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId': {
      id: '/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof QuizSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verification': {
      id: '/_auth/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthVerificationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/terms/': {
      id: '/_public/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof PublicTermsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/features/': {
      id: '/_public/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof PublicFeaturesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about-us/': {
      id: '/_public/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof PublicAboutUsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/parse-cv/': {
      id: '/_app/app/parse-cv/'
      path: '/parse-cv'
      fullPath: '/app/parse-cv/'
      preLoaderRoute: typeof AppAppParseCvIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/history/': {
      id: '/_app/app/history/'
      path: '/history'
      fullPath: '/app/history/'
      preLoaderRoute: typeof AppAppHistoryIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/certification/': {
      id: '/_app/app/certification/'
      path: '/certification'
      fullPath: '/app/certification/'
      preLoaderRoute: typeof AppAppCertificationIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/certificate-verification/': {
      id: '/_app/app/certificate-verification/'
      path: '/certificate-verification'
      fullPath: '/app/certificate-verification/'
      preLoaderRoute: typeof AppAppCertificateVerificationIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/assessment/': {
      id: '/_app/app/assessment/'
      path: '/assessment'
      fullPath: '/app/assessment/'
      preLoaderRoute: typeof AppAppAssessmentIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/account-settings/': {
      id: '/_app/app/account-settings/'
      path: '/account-settings'
      fullPath: '/app/account-settings/'
      preLoaderRoute: typeof AppAppAccountSettingsIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/assessment/$assessmentId': {
      id: '/_app/app/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/app/assessment/$assessmentId'
      preLoaderRoute: typeof AppAppAssessmentAssessmentIdRouteRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/assessment/$assessmentId/': {
      id: '/_app/app/assessment/$assessmentId/'
      path: '/'
      fullPath: '/app/assessment/$assessmentId/'
      preLoaderRoute: typeof AppAppAssessmentAssessmentIdIndexRouteImport
      parentRoute: typeof AppAppAssessmentAssessmentIdRouteRoute
    }
  }
}

interface AppAppAssessmentAssessmentIdRouteRouteChildren {
  AppAppAssessmentAssessmentIdIndexRoute: typeof AppAppAssessmentAssessmentIdIndexRoute
}

const AppAppAssessmentAssessmentIdRouteRouteChildren: AppAppAssessmentAssessmentIdRouteRouteChildren =
  {
    AppAppAssessmentAssessmentIdIndexRoute:
      AppAppAssessmentAssessmentIdIndexRoute,
  }

const AppAppAssessmentAssessmentIdRouteRouteWithChildren =
  AppAppAssessmentAssessmentIdRouteRoute._addFileChildren(
    AppAppAssessmentAssessmentIdRouteRouteChildren,
  )

interface AppAppRouteRouteChildren {
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppAssessmentAssessmentIdRouteRoute: typeof AppAppAssessmentAssessmentIdRouteRouteWithChildren
  AppAppAccountSettingsIndexRoute: typeof AppAppAccountSettingsIndexRoute
  AppAppAssessmentIndexRoute: typeof AppAppAssessmentIndexRoute
  AppAppCertificateVerificationIndexRoute: typeof AppAppCertificateVerificationIndexRoute
  AppAppCertificationIndexRoute: typeof AppAppCertificationIndexRoute
  AppAppHistoryIndexRoute: typeof AppAppHistoryIndexRoute
  AppAppParseCvIndexRoute: typeof AppAppParseCvIndexRoute
}

const AppAppRouteRouteChildren: AppAppRouteRouteChildren = {
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppAssessmentAssessmentIdRouteRoute:
    AppAppAssessmentAssessmentIdRouteRouteWithChildren,
  AppAppAccountSettingsIndexRoute: AppAppAccountSettingsIndexRoute,
  AppAppAssessmentIndexRoute: AppAppAssessmentIndexRoute,
  AppAppCertificateVerificationIndexRoute:
    AppAppCertificateVerificationIndexRoute,
  AppAppCertificationIndexRoute: AppAppCertificationIndexRoute,
  AppAppHistoryIndexRoute: AppAppHistoryIndexRoute,
  AppAppParseCvIndexRoute: AppAppParseCvIndexRoute,
}

const AppAppRouteRouteWithChildren = AppAppRouteRoute._addFileChildren(
  AppAppRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAppRouteRoute: typeof AppAppRouteRouteWithChildren
  AppSplatRoute: typeof AppSplatRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppRouteRoute: AppAppRouteRouteWithChildren,
  AppSplatRoute: AppSplatRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerificationRoute: typeof AuthVerificationRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerificationRoute: AuthVerificationRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAboutUsIndexRoute: typeof PublicAboutUsIndexRoute
  PublicFeaturesIndexRoute: typeof PublicFeaturesIndexRoute
  PublicTermsIndexRoute: typeof PublicTermsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicAboutUsIndexRoute: PublicAboutUsIndexRoute,
  PublicFeaturesIndexRoute: PublicFeaturesIndexRoute,
  PublicTermsIndexRoute: PublicTermsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ParseCVRoute: ParseCVRoute,
  QuizSessionIdRoute: QuizSessionIdRoute,
  ResultSessionIdRoute: ResultSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
